### ISSUE TITLE
下载更新时出错（虽然是上个版本的

### ISSUE THREAD

**Issue by simonsmh** [seven332/Nimingban#86]
TIME=2016-11-18-21-07-58-091 

======== PackageInfo ======== 
PackageName=com.hippo.nimingban 
VersionName=1.2.29 
VersionCode=43 
Signature=C9:27:01:A5:D2:BE:25:4F:F1:E1:AD:39:F0:FD:55:7B:F4:E2:37:31 

======== DeviceInfo ======== 
BOARD=msm8996 
BOOTLOADER=unknown 
CPU_ABI=armeabi-v7a 
CPU_ABI2=armeabi 
DEVICE=OnePlus3 
DISPLAY=OnePlus3-userdebug 7.1 NDE63X 08dce20f99 test-keys 
FINGERPRINT=OnePlus/OnePlus3/OnePlus3:6.0.1/MMB29M/362280:user/release-keys 
HARDWARE=qcom 
HOST=reikou 
ID=NDE63X 
MANUFACTURER=OnePlus 
MODEL=ONEPLUS A3000 
PRODUCT=OnePlus3 
RADIO=2-00002-M8996FAAAANAZM-1.70923.1 
SERIAL=5dc60b19 
TAGS=test-keys 
TYPE=userdebug 
USER=nyyu 
CODENAME=REL 
INCREMENTAL=08dce20f99 
RELEASE=7.1 
SDK=25 

======== CrashInfo ======== 
android.os.FileUriExposedException: file:///storage/emulated/0/nmb/nimingban-1.2.30.apk exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
at android.net.Uri.checkFileUriExposed(Uri.java:2346)
at android.content.Intent.prepareToLeaveProcess(Intent.java:8973)
at android.content.Intent.prepareToLeaveProcess(Intent.java:8934)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
at android.app.ContextImpl.startActivity(ContextImpl.java:791)
at android.app.ContextImpl.startActivity(ContextImpl.java:768)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
at com.hippo.nimingban.client.UpdateHelper$DownloadApkTask.onPostExecute(UpdateHelper.java:158)
at com.hippo.nimingban.client.UpdateHelper$DownloadApkTask.onPostExecute(UpdateHelper.java:111)
at android.os.AsyncTask.finish(AsyncTask.java:660)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6088)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by seven332** [comment]
这是 Android 7 使用了更严格的安全检查导致的。下次更新还会出现这个错误的，下下次才会好。
